name: Build rosetta
#  This workflow is run on pushes to main & every Pull Requests where a .go, .mod, .sum have been changed
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - release/**
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
        ###################
        #### Build App ####
        ###################
      - name: Build
        if: env.GIT_DIFF
        run: GOARCH=${{ matrix.go-arch }} make build
        ###################
        ## Build Tooling ##
        ###################
      - name: Build Rosetta
        if: env.GIT_DIFF
        run: GOARCH=${{ matrix.go-arch }} make rosetta